services:
  writer:
    build: .
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverse-proxy
      - traefik.http.routers.writer.rule=Host(`writer.stefanosamanuel.me`)
      - traefik.http.routers.writer.entrypoints=websecure
      - traefik.http.routers.writer.tls.certresolver=letsencrypt
      - traefik.http.services.writer.loadbalancer.server.port=80
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true
